### ISSUE TITLE
Couldn't reach the server

### ISSUE THREAD

**Issue by Mahmoud87** [ekho/dockerized-tools#1]
Hi Ekho, I just started using your docker image and thanks for the great work, I have installed it as a rockon on rockstor, however when I try to run the webui I get this error message "This site can't be reached". I have tried to use the 8080 and 6881 ports and no luck with either of them. Do you have any ideas what would be the problem? Thanks

**Comment by ekho** [comment]
Hi @Mahmoud87 
I just using it on my home nas and have no problems. 
What `docker ps` command shows after starting container ?

**Comment by Mahmoud87** [comment]
Hi mate, sorry I didn't leave an update to let you know I got it sorted . Thanks for your reply
