### ISSUE TITLE
Speed of Utorrent Docker very slow.

### ISSUE THREAD

**Issue by kiemrong08** [ekho/dockerized-tools#2]
Im test in centos with docker 17.06.0-ce, build 02c1d87

**Comment by ekho** [comment]
What speed do you mean? Download/upload? Web interface?

**Comment by kiemrong08** [comment]
I solved probem. Default setting of this docker in uTorrent setting: Maximum upload rate is `-1`. I just change value to `0` and speed seem like normal.
